### ISSUE TITLE
DPI Awareness

### ISSUE THREAD

**Issue by D1firehail** [D1firehail/AdeptiScanner-GI#2]
By default windows will set 150% DPI ("Change the size of text, apps, and other items") for 4k monitors, which screws up what part of the screen gets grabbed when I screenshot. Problem was noticed in `CaptureScreenshot` call via the Capture button.

For anyone looking at this, until I've fixed it the workaround is to go into display settings and change `Change the size of text, apps, and other items` to 100% for the primary monitor

**Comment by D1firehail** [comment]
Fixed in [V1.1](https://github.com/D1firehail/AdeptiScanner-GI/releases/tag/V1.1)

**Comment by zclimber** [comment]
Looks like it is not fixed completely. I had difficulty scanning items at 125% DPI on 2k display, and after turning scaling off scan works as it should.

**Comment by D1firehail** [comment]
I've already fixed all places II'm aware of where DPI can interfere with the results. If you want to provide me with the information and images I'd need to reproduce and fix the issue let me know. I prefer doing it on discord, but I'm fine with doing it on here if discord isn't an option.
